language: node_js
node_js:
  - 12.18.3

branches:
  only:
  - main

services:
  npm
  docker

script:
  - npm i -g ionic@6.12.3
  - ionic -v
  - ionic build
  - docker --version
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend elsrickle/udagram-frontend:latest

after_success:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push elsrickle/udagram-frontend